services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: encurtaurl_api
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - encurtaurl_net

  postgres:
    image: postgres:16-alpine
    container_name: encurtaurl_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - encurtaurl_net

  redis:
    image: redis:7-alpine
    container_name: encurtaurl_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - encurtaurl_net

volumes:
  postgres_data:
  redis_data:

networks:
  encurtaurl_net:
    driver: bridge
